### ISSUE TITLE
Question about training modal: FileNotFoundError

### ISSUE THREAD

**Issue by AndrewYB** [filby89/body-face-emotion-recognition#2]
when I Train a model using only the skeleton (SEP):use following command:
python main.py --db babyrobot --epochs 200 --step_size 150 --add_body_dnn --num_classes 7 --num_total_iterations=1 --exp_name "BODY-ONLY" --optimizer sgd --weight_decay 1e-3 --lr 1e-1 --batch_size 12 --use_labels body

and The following error occurred：
FileNotFoundError: [Errno 2] No such file or directory: 'BRED_dataset/spontaneous/subject_0/Anger\\openface_output.csv'

Then I open the BRED_dataset,and found that in annotation.csv there are actually exist a path called "BRED_dataset/spontaneous/subject_0/Anger",but this path it is not exist in the dataset.

**Comment by filby89** [comment]
Hi, there is an error in the annotations.csv file. Replace "spontaneous" in the path with "game" and "acted" with "pre-game" to get the correct paths.
I have added this on the dataset page as well (https://zenodo.org/record/3233060) to avoid confusion and will update the csv in the future.

**Comment by majiarong** [comment]
hello，请教您一个问题，我下载 了您的代码，数据集文件夹的名字我也修改了，但是再跑程序的时候出现了一个错误，我已经尝试着解决了三个星期了还是没有想明白错误的原因，您能帮我看看嘛
"D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\python.exe" D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py --db babyrobot --epochs 200 --step_size 150 --add_body_dnn --num_classes 7 --num_total_iterations=1 --exp_name BODY-ONLY --optimizer sgd --weight_decay 1e-3 --lr 1e-1 --batch_size 12 --use_labels body
Namespace(add_body_dnn=True, add_openface_features=False, add_whole_body_branch=False, batch_size=12, body_pooling='avg', confidence_threshold=0.1, db='babyrobot', do_fusion=False, dropout=0.5, epochs=200, exp_name='BODY-ONLY', face_pooling='max', first_layer_size=256, grad_clip=0.1, lr=0.1, momentum=0.9, num_classes=7, num_splits=10, num_total_iterations=1, optimizer='sgd', split_branches=False, step_size=150, use_cnn_features=False, use_labels='body', weight_decay=0.001, weighted_loss=False)
train samples: 196
[41 33 27 30 40 25]
[41 29 27 15 39 22 23]
[ 9 16 12 29 16 18 96]
test samples: 19
[4 2 3 3 4 3]
[4 2 3 1 4 2 3]
[0 1 2 3 2 3 8]
scaled data
D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\optim\lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 490, in <module>
    b.run()
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 45, in run
    val_top_all, val_top_body, val_top_face, p, r, f = self.cross_validation(num_splits=args.num_splits)
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 137, in cross_validation
    val_top_all, val_top_body, val_top_face, p, r, f = self.fit(self.model)
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 191, in fit
    train_acc, train_loss = self.train_epoch()
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 275, in train_epoch
    out = self.model.forward((face, body, hand_right, hand_left, length, facial_cnn_features))
  File "D:\jiarong\xiwang\419\新建文件夹\body-face-emotion-recognition-master\models.py", line 179, in forward
    static_features = self.static(static_features)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Process finished with exit code 1

**Comment by majiarong** [comment]
hello,Please tell you a question, I downloaded your code, I also modified the name of the data set folder, but when I ran the program again, an error occurred. I have tried to solve it for three weeks and I still haven’t figured out the error. The reason, can you help me see


"D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\python.exe" D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py --db babyrobot --epochs 200 --step_size 150 --add_body_dnn --num_classes 7 --num_total_iterations=1 --exp_name BODY-ONLY --optimizer sgd --weight_decay 1e-3 --lr 1e-1 --batch_size 12 --use_labels body
Namespace(add_body_dnn=True, add_openface_features=False, add_whole_body_branch=False, batch_size=12, body_pooling='avg', confidence_threshold=0.1, db='babyrobot', do_fusion=False, dropout=0.5, epochs=200, exp_name='BODY-ONLY', face_pooling='max', first_layer_size=256, grad_clip=0.1, lr=0.1, momentum=0.9, num_classes=7, num_splits=10, num_total_iterations=1, optimizer='sgd', split_branches=False, step_size=150, use_cnn_features=False, use_labels='body', weight_decay=0.001, weighted_loss=False)
train samples: 196
[41 33 27 30 40 25]
[41 29 27 15 39 22 23]
[ 9 16 12 29 16 18 96]
test samples: 19
[4 2 3 3 4 3]
[4 2 3 1 4 2 3]
[0 1 2 3 2 3 8]
scaled data
D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\optim\lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 490, in <module>
    b.run()
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 45, in run
    val_top_all, val_top_body, val_top_face, p, r, f = self.cross_validation(num_splits=args.num_splits)
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 137, in cross_validation
    val_top_all, val_top_body, val_top_face, p, r, f = self.fit(self.model)
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 191, in fit
    train_acc, train_loss = self.train_epoch()
  File "D:/jiarong/xiwang/419/新建文件夹/body-face-emotion-recognition-master/main.py", line 275, in train_epoch
    out = self.model.forward((face, body, hand_right, hand_left, length, facial_cnn_features))
  File "D:\jiarong\xiwang\419\新建文件夹\body-face-emotion-recognition-master\models.py", line 179, in forward
    static_features = self.static(static_features)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\ce\lib\site-packages\torch\nn\functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Process finished with exit code 1

**Comment by filby89** [comment]
Hi, can you try to run the code without cuda (on cpu)? There seems to be a problem with an fc layer dimensions.

**Comment by majiarong** [comment]
Thank you. I have installed the latest CUDA and the corresponding torch, and have run out the results.&nbsp;
Excuse me ,How do you get the form of openpose? Can you provide the code (I put the form in the attachment)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filby89/body-face-emotion-recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filby89/body-face-emotion-recognition] Question about training modal: FileNotFoundError (#2)





 
Hi, can you try to run the code without cuda (on cpu)? There seems to be a problem with an fc layer dimensions.

**Comment by filby89** [comment]
You can get openpose from here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose

I have run openpose for each video in the dataset and got the keypoints in json format. An example on how to run openpose is shown in their repo:

``
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/
``

**Comment by majiarong** [comment]
Thank you very much for your answer! Thank you! Your answer is very helpful to me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filby89/body-face-emotion-recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filby89/body-face-emotion-recognition] Question about training modal: FileNotFoundError (#2)





 
You can get openpose from here:
 https://github.com/CMU-Perceptual-Computing-Lab/openpose
 
I have run openpose for each video in the dataset and got the keypoints in json format. An example on how to run openpose is shown in their repo:
 
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/

**Comment by majiarong** [comment]
Hello!Do you still have the references in your published articles ? Can you share it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filby89/body-face-emotion-recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filby89/body-face-emotion-recognition] Question about training modal: FileNotFoundError (#2)





 
You can get openpose from here:
 https://github.com/CMU-Perceptual-Computing-Lab/openpose
 
I have run openpose for each video in the dataset and got the keypoints in json format. An example on how to run openpose is shown in their repo:
 
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/

**Comment by filby89** [comment]
Hi, I am not sure I understand what you mean!

**Comment by AndrewYB** [comment]
> Hi, there is an error in the annotations.csv file. Replace "spontaneous" in the path with "game" and "acted" with "pre-game" to get the correct paths.
> I have added this on the dataset page as well (https://zenodo.org/record/3233060) to avoid confusion and will update the csv in the future.

Thank you very much

**Comment by bernie6401** [comment]
Hi, I have a problem when I run the basic code in my cmd. BTW, I changed the data path in the csv and I rename the folder that down the BRED_dataset named pre_game to pre-game(I got something wrong here). But I still got an error for RuntimeError. The following message is what I got from cmd...
My GPU is RTX-3070
CUDA 11.2


#-----------------------------error message-----------------------------#
(Special Topic in DL_IR) D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master>python main.py --db babyrobot --epochs 200 --step_size 150 --add_body_dnn --num_classes 7 --num_total_iterations=1 --exp_name "BODY-ONLY" --optimizer sgd --weight_decay 1e-3 --lr 1e-1 --batch_size 12 --use_labels body5656
Namespace(add_body_dnn=True, add_openface_features=False, add_whole_body_branch=False, batch_size=12, body_pooling='avg', confidence_threshold=0.1, db='babyrobot', do_fusion=False, dropout=0.5, epochs=200, exp_name='BODY-ONLY', face_pooling='max', first_layer_size=256, grad_clip=0.1, lr=0.1, momentum=0.9, num_classes=7, num_splits=10, num_total_iterations=1, optimizer='sgd', split_branches=False, step_size=150, use_cnn_features=False, use_labels='body5656', weight_decay=0.001, weighted_loss=False)
train samples: 196
[41 33 27 30 40 25]
[41 29 27 15 39 22 23]
[ 9 16 12 29 16 18 96]
test samples: 19
[4 2 3 3 4 3]
[4 2 3 1 4 2 3]
[0 1 2 3 2 3 8]
scaled data
D:\Anaconda-new\envs\Special Topic in DL_IR\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Namespace(add_body_dnn=True, add_openface_features=False, add_whole_body_branch=False, batch_size=12, body_pooling='avg', confidence_threshold=0.1, db='babyrobot', do_fusion=False, dropout=0.5, epochs=200, exp_name='BODY-ONLY', face_pooling='max', first_layer_size=256, grad_clip=0.1, lr=0.1, momentum=0.9, num_classes=7, num_splits=10, num_total_iterations=1, optimizer='sgd', split_branches=False, step_size=150, use_cnn_features=False, use_labels='body5656', weight_decay=0.001, weighted_loss=False)
train samples: 196
[41 33 27 30 40 25]
[41 29 27 15 39 22 23]
[ 9 16 12 29 16 18 96]
test samples: 19
[4 2 3 3 4 3]
[4 2 3 1 4 2 3]
[0 1 2 3 2 3 8]
scaled data
D:\Anaconda-new\envs\Special Topic in DL_IR\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master\main.py", line 489, in <module>
    b.run()
  File "D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master\main.py", line 45, in run
    val_top_all, val_top_body, val_top_face, p, r, f = self.cross_validation(num_splits=args.num_splits)
  File "D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master\main.py", line 137, in cross_validation
    val_top_all, val_top_body, val_top_face, p, r, f = self.fit(self.model)
  File "D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master\main.py", line 191, in fit
    train_acc, train_loss = self.train_epoch()
  File "D:\NTUST\Project\Special Topic\Model\body-face-emotion-recognition-master\main.py", line 223, in train_epoch
    for i, batch in enumerate(self.dataloader_train):
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda-new\envs\Special Topic in DL_IR\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
**RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.**
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFBF84F3B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFC64B5B3E3  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFC66307034  Unknown               Unknown  Unknown
ntdll.dll          00007FFC671A2651  Unknown               Unknown  Unknown
#-----------------------------error message-----------------------------#

Could u please take a look and I'll very appreciate.
If u need any info. of my hardware, please let me know. Thanks a lot

**Comment by onniew** [comment]
> 

i had the same question and i solved it by reducing the batch size to 3
it works for me
hopefully it helps

**Comment by majiarong** [comment]
您好，来信已收到。
